//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.31 at 01:23:33 PM PDT 
//

package com.dashboard.domain.objects;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Servers }
     * 
     */
    public Servers createServers() {
        return new Servers();
    }

    /**
     * Create an instance of {@link Servers.Addresses }
     * 
     */
    public Servers.Addresses createServersAddresses() {
        return new Servers.Addresses();
    }

    /**
     * Create an instance of {@link Servers.Image }
     * 
     */
    public Servers.Image createServersImage() {
        return new Servers.Image();
    }

    /**
     * Create an instance of {@link Servers.Flavor }
     * 
     */
    public Servers.Flavor createServersFlavor() {
        return new Servers.Flavor();
    }

    /**
     * Create an instance of {@link Servers.SecurityGroups }
     * 
     */
    public Servers.SecurityGroups createServersSecurityGroups() {
        return new Servers.SecurityGroups();
    }

    /**
     * Create an instance of {@link Servers.Addresses.Net2 }
     * 
     */
    public Servers.Addresses.Net2 createServersAddressesNet2() {
        return new Servers.Addresses.Net2();
    }

}
